# This is a basic workflow to help you get started with Actions

name: GENERATE GIST README

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: # 触发时机
  push:
    branches: [main] # master有更新
  schedule:
    - cron: "0 4 */7 * *" # 每天0点运行
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest # 使用最新版ubuntu镜像

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python # 安装python环境
        uses: actions/setup-python@v2

      - name: Install Python dependencies # 安装python爬虫依赖包
        run: python -m pip install requests

      - name: Run python # 生成新的README.md文件
        run: python generateGistsList.py

      - name: Commit and push if changed # 将README.md更新到仓库
        run: |
          git diff
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Updated" || exit 
          git push
